### PR TITLE
Updated .plgx for KeePass 2.30

### PR DESCRIPTION
**Pull request by Sebb767**
Recompiled the .plgx in order to update it for KeePass 2.30 and finally include PR [#217](https://github.com/pfn/keepasshttp/pull/217) (configureable http host).

This was compiled & tested on Linux (Ubuntu) with Mono 4.0.2 and KeePass 2.30 portable, but the extension should work for all plattforms :)

Checksums of `KeePassHttp.pglx`:
<pre>md5:    db81be636223b7a7850b449915c7a16b
sha1:   45f66da88809c1b07a8e7b6987e46ac34cbb5219
sha256: d599149c6a43a38af59113a7fe33c1894c7adc4d7301b6eac81d88d849390138</pre>

### CODE REVIEW

**Comment by nifr** [comment]
awesome.

**Comment by skobkin** [comment]
Will it be merged?

**Comment by pfn** [comment]
There's no need to re-build plgx for 2.30, I will not merge binaries. #271 will be merged separately once I have a chance to review.

**Comment by skobkin** [comment]
@pfn Can you suggest what to do if I getting this message on keepass startup:


At the same time, despite of the error I can enter KeepassHttp settings. But browser extension can't connect to KeePass so I getting "pressed" extension button state and no popup window.

Can I test extension for example via curl to determine where is the problem? Where I can find some API examples or documentation?

**Comment by Sebb767** [comment]
That error was pretty much the reason for this PR :) The recompiled binaries fixed this for me. 

I did a quick review of #271 beforehand, but I understand if you don't trust my binaries of course.

**Comment by skobkin** [comment]
> but I do fully understand that you don't trust 'foreign' binaries of course.
So I can review and compile the plugin myself :)
I will check will it fix the problem for me on not. Thank you.

**Comment by skobkin** [comment]
@Sebb767 #271? Or #217?
Unfortunately, #217 does not fix the problem I have.

**Comment by Sebb767** [comment]
@skobkin I meant #217. The fix for my problem was actually recompiling it (on my ubuntu chroot). That's the binary I shared in this PR :) If you don't trust my binary (you can, I do _not_ mean that it's tainted in any way) recompiling it yourself isn't that hard.

The "official" extension binary was working only with KeePass 2.29; with 2.30 would throw pretty much the same error you described above and not load the plugin. To get the working binary compiling it with KP 2.30 was sufficient, no further action was required (merging #217 was optional).

#217 did actually fix my problem, since without being able to change the listener host there was no way to get the chrome extension connected on my Chromebook, but this had nothing to do with the version error. #217 did work with 2.29 iirc, however.

**Comment by skobkin** [comment]
> recompiling it yourself isn't that hard.

I already tested #217 branch by compiling it myself. It does not solve my problem as you note below.

> To get the working binary compiling it with KP 2.30 was sufficient, no further action was required (merging #217 was optional).

Did not helped me. May be I done something wrong.

**Comment by Sebb767** [comment]
Thats strange. 

Sorry for the late answer, but did you test whether you're compiling with the version you want to compile for?

I had the same problem when setting up and I found out that somehow I had KP 2.29 in my path.
$ keepass2 --version 
should to verify this. Or use a relative path when compiling. Also, did you clear previous plugin versions from the KP folders? That would explain why it works despite the warning, its loaded twice.

**Comment by skobkin** [comment]
It's strange but after reboot I got plugin working. I didn't understand what have I done to fix this. I did many things when tried to fix it. Don't know which one was helped.

Sorry for distraction.

**Pull request closed without merging**
