### PR TITLE
Allow the host to bind to to be changed.

### PR DESCRIPTION
**Pull request by frankhommers**
This would also solve https://github.com/pfn/keepasshttp/issues/157

### CODE REVIEW

**Comment by pfn** [comment]
Can you update the pr such that the diffs aren't completely showing as changed? (whitespace and indentation). As is, this is fairly difficult to review. Thanks

**Comment by frankhommers** [comment]
@pfn What are your settings? Keep tabs, use spaces, indentation width? etc...? I couldn't really determine it by looking at your files.

**Comment by pfn** [comment]
The point is to not change line endings/indentation/tabs on lines that you do not change. Perhaps it's a crlf issue, maybe set core.autocrlf=true

**Comment by frankhommers** [comment]
It was a tab issue. I was using "Use tabs" and you are using "Keep spaces". I have made a new PR.

**Pull request closed without merging**
