### PR TITLE
Add a copy of the GPL v3 Licence text

### PR DESCRIPTION
**Pull request by chrestomanci**
Fixes issue #247

### CODE REVIEW

**Comment by chrestomanci** [comment]
Please note. I am not an author of keepasshttp. I do not have any authority to say what licence the software has. Please do not assume that the GPL licence is the correct one, unless the maintainer merges this pull request to master.

I created this pull request in response to issue #247 because I think that the question will happen again unless a licence file is included in the main source tree.

**Comment by pfn** [comment]
Should be named ` LICENSE`

**Comment by chrestomanci** [comment]
I find that both LICENSE and COPYING are common file names for the software licence. I chose COPYING because that is the traditional name, but if you prefer LICENSE then it is up to you. I would be happy to rename the file if you ask me to, or you can before you merge.

The important point is to make sure that the licence is spelt out clearly, so there can be no confusion. The best way to do that it to put a copy of the licence text in the source tree. The exact file name does not matter much.

**Comment by pfn** [comment]
I would like it named license. Thanks

**Comment by chrestomanci** [comment]
Bump

**Pull request merged**
